import { test, expect } from '@playwright/test';
import path from 'path';
import {
  SchoolAdminBulkFormsPage,
  BULK_FORM_URLS,
} from '../pages/SchoolAdminBulkFormsPage';

/**
 * NEMO-24311 — [Regression] Warning message modal when navigating away from a
 * bulk "add students" form.
 *
 * Runs as the MQA Sierra school admin from the test data
 * (asgardmqaadmin1@mailsac.com). That user differs from the global-setup login,
 * so this file consumes a dedicated storage state generated by
 * testcontexts/NEMO-24311/generate-auth.mjs.
 */
test.use({ storageState: 'auth/storageState.nemo24311.json' });

const DATA = path.resolve(__dirname, '../testcontexts/NEMO-24311');
const CSV = {
  child: path.join(DATA, 'child_usernames.csv'),
  adult: path.join(DATA, 'adult_usernames.csv'),
  adultEmail: path.join(DATA, 'adult_emails.csv'),
  existingChild: path.join(DATA, 'existing_child_usernames.csv'),
};

const EMAIL_BODY =
  'You have not finished adding new students/teachers yet, but this form has been saved for you.';
const EXISTING_CHILD_BODY =
  'You have not finished adding students yet, but this form has been saved for you';

// read the rendered <input> values (form rows are bound via JS, not attributes).
// Form-agnostic: input ids differ between the child / adult / existing forms,
// so read every text input's value rather than relying on an id prefix.
const allInputValues = (page: import('@playwright/test').Page) =>
  page.evaluate(() =>
    Array.from(document.querySelectorAll<HTMLInputElement>('input'))
      .map((el) => el.value)
      .filter(Boolean),
  );

async function fillAdultEmailRow(
  page: import('@playwright/test').Page,
  email: string,
) {
  await page.getByRole('textbox', { name: "Student's Email" }).first().fill(email);
  const first = page.getByRole('textbox', { name: "Student's first name" }).first();
  await expect(first).toBeEnabled();
  await first.fill('Nemo');
  await page.getByRole('textbox', { name: "Student's last name" }).first().fill('Student');
  // The form autosaves and re-renders, which can dismiss the role dropdown
  // mid-click; retry opening it + selecting until the choice sticks.
  const roleField = page.getByRole('textbox', { name: 'Select role' }).first();
  const studentOption = page.getByRole('link', { name: 'student', exact: true }).first();
  await expect(async () => {
    await roleField.click();
    await studentOption.click({ timeout: 3000 });
    await expect(studentOption).toBeHidden({ timeout: 2000 }); // dropdown closed = selected
  }).toPass({ timeout: 25000 });
}

test.describe('NEMO-24311 — bulk form leave-page warning modal', () => {
  test.setTimeout(90_000);

  let app: SchoolAdminBulkFormsPage;
  test.beforeEach(({ page }) => {
    app = new SchoolAdminBulkFormsPage(page);
  });

  test('TC-001 Warning modal after CSV upload — new_child_username (CUP logo)', async ({ page }) => {
    await app.goto('new_child_username');
    await app.uploadCsv(CSV.child);
    await expect.poll(() => allInputValues(page)).toContain('Nemo');
    await app.cupLogo.click();
    await app.expectWarningModal();
  });

  test('TC-002 No modal when form empty — new_child_username', async ({ page }) => {
    await app.goto('new_child_username');
    await app.cupLogo.click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();
  });

  test('TC-003 Warning modal after CSV upload — new_adult_username (CUP logo)', async ({ page }) => {
    await app.goto('new_adult_username');
    await app.uploadCsv(CSV.adult);
    await expect.poll(() => allInputValues(page)).toContain('Nemo');
    await app.cupLogo.click();
    await app.expectWarningModal();
  });

  test('TC-005 Warning modal after manual edit — new_adult_email (CUP logo)', async ({ page }) => {
    await app.goto('new_adult_email');
    await fillAdultEmailRow(page, 'cqatestaiuser1@mailsac.com');
    await app.cupLogo.click();
    await app.expectLeaveModal(EMAIL_BODY);
  });

  test('TC-006 Warning modal after CSV upload — new_adult_email (CUP logo)', async ({ page }) => {
    await app.goto('new_adult_email');
    await app.uploadCsv(CSV.adultEmail);
    await expect.poll(() => allInputValues(page)).toContain('cqatestaiuser2@mailsac.com');
    await app.cupLogo.click();
    await app.expectLeaveModal(EMAIL_BODY);
  });

  test('TC-007 Warning modal after manual edit — existing_child_username (CUP logo)', async ({ page }) => {
    await app.goto('existing_child_username');
    await page.getByRole('textbox', { name: 'Class key' }).first().fill('F32y-gMFU');
    await app.cupLogo.click();
    await app.expectLeaveModal(EXISTING_CHILD_BODY);
  });

  test('TC-008 Warning modal after CSV upload — existing_child_username (CUP logo)', async ({ page }) => {
    await app.goto('existing_child_username');
    await app.uploadCsv(CSV.existingChild);
    await expect.poll(() => allInputValues(page)).toContain('cqatestaichild1');
    await app.cupLogo.click();
    await app.expectLeaveModal(EXISTING_CHILD_BODY);
  });

  test('TC-009 Warning modal after manual edit — existing_adult_email (CUP logo)', async ({ page }) => {
    await app.goto('existing_adult_email');
    await page.getByRole('textbox', { name: 'Class key' }).first().fill('F32y-gMFU');
    await app.cupLogo.click();
    await app.expectLeaveModal(EMAIL_BODY);
  });

  test('TC-010 My profile and Logout also trigger the modal', async ({ page }) => {
    await app.goto('new_adult_email');
    await fillAdultEmailRow(page, 'cqatestaiuser1@mailsac.com');

    await app.openAccountMenu();
    await app.myProfileLink.click();
    await app.expectLeaveModal(EMAIL_BODY);
    await app.leaveDialog.getByText('Back to form').click();

    await app.openAccountMenu();
    await app.logoutButton.click();
    await app.expectLeaveModal(EMAIL_BODY);
  });

  test('TC-011a Yes, leave the page discards data — new_child_username', async ({ page }) => {
    await app.goto('new_child_username');
    await app.uploadCsv(CSV.child);
    await app.cupLogo.click();
    await app.warningDialog.getByRole('link', { name: 'Yes, leave the page' }).click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.goto('new_child_username');
    await expect.poll(() => allInputValues(page)).not.toContain('Nemo'); // discarded
  });

  test('TC-011b Yes, leave the page discards data — new_adult_username', async ({ page }) => {
    await app.goto('new_adult_username');
    await app.uploadCsv(CSV.adult);
    await app.cupLogo.click();
    await app.warningDialog.getByRole('link', { name: 'Yes, leave the page' }).click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_adult_username);
    await app.goto('new_adult_username');
    await expect.poll(() => allInputValues(page)).not.toContain('Nemo'); // discarded
  });

  test('TC-011c I\'ll return later saves data — new_adult_email', async ({ page }) => {
    const email = 'cqatestaiuser1@mailsac.com';
    await app.goto('new_adult_email');
    await fillAdultEmailRow(page, email);
    await app.cupLogo.click();
    await app.leaveDialog.getByText("I'll return later").click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_adult_email);
    await app.goto('new_adult_email');
    await expect.poll(() => allInputValues(page)).toContain(email);
  });

  test('TC-011d I\'ll return later saves data — existing_child_username', async ({ page }) => {
    await app.goto('existing_child_username');
    await page.getByRole('textbox', { name: 'Class key' }).first().fill('F32y-gMFU');
    await app.cupLogo.click();
    await app.leaveDialog.getByText("I'll return later").click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.existing_child_username);
    await app.goto('existing_child_username');
    await expect(page.getByRole('textbox', { name: 'Class key' }).first()).toHaveValue('F32y-gMFU');
  });

  test('TC-012 Back to form keeps user on form with data intact', async ({ page }) => {
    await app.goto('new_child_username');
    await app.uploadCsv(CSV.child);
    await app.cupLogo.click();
    await app.warningDialog.getByRole('link', { name: 'No, go back to the form' }).click();
    await expect(page).toHaveURL(BULK_FORM_URLS.new_child_username);
    await app.expectNoModal();
    await expect.poll(() => allInputValues(page)).toContain('Nemo');
  });

  test('TC-014 Modal content and buttons correct per form type', async ({ page }) => {
    // 1. username-create form -> "Warning" (data lost)
    await app.goto('new_child_username');
    await app.uploadCsv(CSV.child);
    await app.cupLogo.click();
    await app.expectWarningModal();
    await app.warningDialog.getByRole('link', { name: 'Yes, leave the page' }).click();

    // 2. adult-email form -> "Leave this page?" (.../new students/teachers...)
    await app.goto('new_adult_email');
    await fillAdultEmailRow(page, 'cqatestaiuser1@mailsac.com');
    await app.cupLogo.click();
    await app.expectLeaveModal(EMAIL_BODY);
    await app.leaveDialog.getByText('Back to form').click();

    // 3. existing-child form -> "Leave this page?" (.../students...) + X close icon
    await app.goto('existing_child_username');
    await page.getByRole('textbox', { name: 'Class key' }).first().fill('F32y-gMFU');
    await app.cupLogo.click();
    await app.expectLeaveModal(EXISTING_CHILD_BODY);
    await expect(app.leaveDialog.getByRole('button', { name: 'Close' })).toBeVisible();
  });

  test('TC-NEW-1 < Back link triggers the modal', async ({ page }) => {
    await app.goto('new_child_username');
    await app.uploadCsv(CSV.child);
    await app.backLink.click();
    await app.expectWarningModal();
    await app.warningDialog.getByRole('link', { name: 'No, go back to the form' }).click();
    await expect.poll(() => allInputValues(page)).toContain('Nemo');
  });

  test('TC-NEW-2 No modal when clicking a notification', async ({ page }) => {
    // Expected per spec: clicking a notification on a dirty bulk form does NOT
    // show the warning modal; navigation proceeds.
    await app.goto('new_child_username');
    await app.uploadCsv(CSV.child);
    await app.clickFirstNotification();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();
  });

  test('TC-NEW-3 No modal when form empty — all navigation triggers', async ({ page }) => {
    // CUP logo
    await app.goto('new_child_username');
    await app.cupLogo.click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();

    // < Back link
    await app.goto('new_child_username');
    await app.backLink.click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();

    // notification
    await app.goto('new_child_username');
    await app.clickFirstNotification();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();

    // My profile
    await app.goto('new_child_username');
    await app.openAccountMenu();
    await app.myProfileLink.click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();

    // Logout
    await app.goto('new_child_username');
    await app.openAccountMenu();
    await app.logoutButton.click();
    await expect(page).not.toHaveURL(BULK_FORM_URLS.new_child_username, { timeout: 15000 });
    await app.expectNoModal();
  });
});
