import type { Reporter, TestCase, TestResult } from '@playwright/test/reporter';
import fs from 'fs';

interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
  assignee: string;
}

interface GitHubSearchResponse {
  total_count: number;
}

interface GitHubIssueResponse {
  number: number;
  html_url: string;
  message?: string;
}


// eslint-disable-next-line no-control-regex
const ANSI_RE = /[][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><~]/g;

function stripAnsi(s: string): string {
  return s.replace(ANSI_RE, '');
}

export default class GitHubIssueReporter implements Reporter {
  private config: GitHubConfig | null = null;
  private handledTitles = new Set<string>();

  constructor() {
    const token = process.env.GITHUB_TOKEN ?? '';
    const repoStr = process.env.GITHUB_REPO ?? '';
    const [owner = '', repo = ''] = repoStr.split('/');
    const assignee = process.env.GITHUB_ASSIGNEE ?? '';

    if (token && owner && repo) {
      this.config = { token, owner, repo, assignee };
    } else {
      console.warn(
        '\n[GitHubIssueReporter] DISABLED — set GITHUB_TOKEN, GITHUB_REPO (owner/repo), and GITHUB_ASSIGNEE to enable automatic issue creation.\n',
      );
    }
  }

  async onTestEnd(test: TestCase, result: TestResult): Promise<void> {
    if (!this.config || result.status !== 'failed') return;

    const suiteName = test.parent?.title ?? '';
    const issueTitle = `[Issue] ${suiteName}: ${test.title}`;

    if (this.handledTitles.has(issueTitle)) return;
    this.handledTitles.add(issueTitle);

    if (await this.findOpenIssue(issueTitle)) {
      console.log(`[GitHubIssueReporter] Skipped — open issue already exists: "${issueTitle}"`);
      return;
    }

    const screenshot = result.attachments.find(
      a => a.name === 'screenshot' && a.contentType === 'image/png' && a.path,
    );

    let screenshotUrl: string | null = null;
    if (screenshot?.path) {
      screenshotUrl = await this.uploadScreenshot(screenshot.path);
    }

    await this.createIssue(issueTitle, this.buildBody(test, result, screenshotUrl));
  }

  // Extract only Expected/Received lines from the error message.
  private parseError(message: string): string {
    const lines = stripAnsi(message).split('\n');
    const relevant = lines.filter(l => {
      const t = l.trim();
      return (
        t.startsWith('Expected pattern:') ||
        t.startsWith('Expected string:') ||
        t.startsWith('Received string:') ||
        t.startsWith('Received value:')
      );
    });
    return relevant
      .map(l => l.trim().replace(/^(Expected pattern:\s*)\/(.+)\/$/, '$1"$2"'))
      .join('\n') || stripAnsi(lines[0] ?? '').trim();
  }

  // Extract the "unexpected value" line from the call log and the first
  // relevant "at" frame from the stack.
  private parseStack(message: string, stack: string): string {
    const msgLines = stripAnsi(message).split('\n');
    const stackLines = stripAnsi(stack).split('\n');
    const result: string[] = [];

    for (const line of msgLines) {
      const t = line.trim();
      if (t.includes('unexpected value')) {
        result.push(t.replace(/^-\s*/, ''));
      }
    }

    for (const line of stackLines) {
      const t = line.trim();
      if (t.startsWith('at ') && !t.includes('node_modules') && !t.includes('playwright')) {
        result.push(t);
        break;
      }
    }

    return result.join('\n');
  }

  private buildBody(test: TestCase, result: TestResult, screenshotUrl: string | null): string {
    const titlePath = test.titlePath().filter(Boolean);
    const browser = titlePath[0] ?? 'unknown';
    const file = test.location.file;
    const line = test.location.line;
    const error = result.errors[0];
    const errorMsg = error?.message ?? 'No error message';
    const stack = error?.stack ?? '';

    const errorSection = this.parseError(errorMsg);
    const stackSection = this.parseStack(errorMsg, stack);

    const parts = [
      `## Automation Test Failure`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| **Test** | ${titlePath.slice(1).join(' › ')} |`,
      `| **Browser** | ${browser} |`,
      `| **File** | \`${file}:${line}\` |`,
      `| **Duration** | ${(result.duration / 1000).toFixed(2)}s |`,
      `| **Time (UTC)** | ${new Date().toISOString()} |`,
      ``,
      `### Error`,
      `\`\`\``,
      errorSection,
      `\`\`\``,
      ``,
      `### Stack Trace`,
      `\`\`\``,
      stackSection || '(no stack trace)',
      `\`\`\``,
    ];

    if (screenshotUrl) {
      parts.push(``, `### Screenshot`, ``, `![Failure screenshot](${screenshotUrl})`);
    }

    parts.push(``, `---`, `*Auto-generated by Playwright GitHub Issue Reporter*`);

    return parts.join('\n');
  }

  private async uploadScreenshot(screenshotPath: string): Promise<string | null> {
    const { owner, repo } = this.config!;
    try {
      const base64 = fs.readFileSync(screenshotPath).toString('base64');
      const filePath = `test-screenshots/failure-${Date.now()}.png`;

      const res = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
        {
          method: 'PUT',
          headers: { ...this.authHeaders(), 'Content-Type': 'application/json' },
          body: JSON.stringify({
            message: 'chore: add test failure screenshot',
            content: base64,
          }),
        },
      );

      if (!res.ok) {
        const text = await res.text();
        console.error(`[GitHubIssueReporter] Screenshot upload failed (HTTP ${res.status}): ${text}`);
        return null;
      }

      const data = (await res.json()) as { content: { download_url: string } };
      return data.content.download_url;
    } catch (err) {
      console.error('[GitHubIssueReporter] Screenshot upload error:', err);
      return null;
    }
  }

  private async findOpenIssue(title: string): Promise<boolean> {
    const { owner, repo } = this.config!;
    const q = encodeURIComponent(
      `repo:${owner}/${repo} is:issue is:open label:automation-failure in:title "${title}"`,
    );
    try {
      const res = await fetch(
        `https://api.github.com/search/issues?q=${q}&per_page=1`,
        { headers: this.authHeaders() },
      );
      if (!res.ok) return false;
      const data = (await res.json()) as GitHubSearchResponse;
      return data.total_count > 0;
    } catch {
      return false;
    }
  }

  private async createIssue(title: string, body: string): Promise<void> {
    const { owner, repo, assignee } = this.config!;
    const payload: Record<string, unknown> = {
      title,
      body,
      labels: ['automation-failure'],
    };
    if (assignee) payload.assignees = [assignee];

    try {
      const res = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/issues`,
        {
          method: 'POST',
          headers: { ...this.authHeaders(), 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        },
      );
      const data = (await res.json()) as GitHubIssueResponse;
      if (res.ok) {
        console.log(`[GitHubIssueReporter] Issue #${data.number} created: ${data.html_url}`);
      } else {
        console.error(
          `[GitHubIssueReporter] Failed to create issue (HTTP ${res.status}): ${data.message ?? JSON.stringify(data)}`,
        );
      }
    } catch (err) {
      console.error('[GitHubIssueReporter] Network error:', err);
    }
  }

  private authHeaders(): Record<string, string> {
    return {
      Authorization: `Bearer ${this.config!.token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    };
  }
}
